# 实验5-Numpy和Pandas基础🐿️

<table style="margin: 0 auto;"> 
    <tr> 
        <td>班级</td> <td> 24计科 </td> 
    </tr> 
    <tr> 
        <td>学号</td> <td>    </td> 
    </tr> 
    <tr> 
        <td>姓名</td> <td>   </td> 
    </tr> 
</table>

- 向量化
- Numpy
- Pandas

## 实验注意事项

1. 请在指定的地方按照实验指导要求来编写代码。
2. 请按照实验指导要求使用指定的变量名或函数名，不要使用其他的名字。
3. 不要添加任何额外的语句。
4. 不要添加任何额外的代码单元格。
5. 不要在不需要的地方修改作业代码，比如创建额外的变量，修改测试文件中的代码。
6. 实验指导中的`...`表示需要你补充代码的部分，其他部分的代码不用修改。
7. 代码提示中会给出估计的代码行数，例如大约1行代码，估计的代码行数只是一个参考值，实际编写时可能会有出入，请根据实际情况来编写。
8. 请独立完成作业，禁止抄袭，发现抄袭行为成绩记零分

In [1]:
# 导入测试代码
from testset5 import *

## 向量化（Vectorization）

`Numpy`和`Pandas`在数据分析和机器学习中都被大量地使用，通常逆需要处理非常大的数据集。因此，一个非计算高效的函数可能会成为算法中的巨大瓶颈，为了确保代码具有计算效率，你需要使用向量化操作。

- 利用`numpy`和`pandas`的函数或操作对整个数组或数组的子集进行操作
- 尽可能避免使用`for`循环和`while`循环逐个处理数据集中的元素
- 向量化操作的编程范式在数据分析、机器学习领域被大量地使用，例如下面这些最流行的深度学习框架
  - `pytorch`
  - `tensorflow`
  - ...  

## Numpy🐍

In [2]:
# 安装numpy模块
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


### 为什么需要Numpy❓

- 运行速度：NumPy提供了高效的数组操作功能(向量化操作)，可以对大规模的数据进行快速的计算和处理
- 方便使用: 处理数据的过程更加简洁和高效
- 功能丰富：提供了丰富的函数库，可以方便地进行数值计算和统计分析。

In [3]:
# 导入numpy
import numpy as np
np.random.seed(12345)

In [4]:
# 长度100万的numpy格式的数组
my_arr = np.arange(1_000_000)

# 长度100万的list
my_list = list(range(1_000_000))

- 计算数组中一百万个数的平方，使用`timeit`测试两种方法的运行时间
- 结论：因为`numpy`的向量化操作，所以运行速度远远快过使用for循环的list。

In [5]:
# print('numpy running time:')
# %timeit my_arr2 = my_arr ** 2

# print('\npython list running time:')
# %timeit my_list2 = [x ** 2 for x in my_list]

### Numpy ndarray数据结构

numpy只有一种数据结构：ndarray，它是一个多维数组，每个元素都是相同类型的。

![ndarray](./img/2023-10-27-11-02-03.png)

In [6]:
import numpy as np

data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [7]:
# ndarray的数据类型,数组只能包含相同类型的数据
data.dtype

dtype('int32')

### 创建ndarray

![create ndarray](./img/2023-10-27-11-06-02.png)

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.random.random(3)

array([0.92961609, 0.31637555, 0.18391881])

In [11]:
# 类似Python中的range函数
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 算术运算

![加法运算](./img/2023-10-27-11-16-15.png)

In [12]:
import numpy as np
data = np.array([1, 2, 3])
ones = np.array([1, 1, 100])
data + ones

array([  2,   3, 103])

![其他运算](./img/2023-10-27-11-18-34.png)

In [13]:
data - ones

array([  0,   1, -97])

In [14]:
data * data

array([1, 4, 9])

In [15]:
data / data

array([1., 1., 1.])

In [16]:
data = np.array([2, 3])
print(data)
data ** data

[2 3]


array([ 4, 27])

![乘以一个数](./img/2023-10-27-11-20-07.png)

In [17]:
data * 1.6

array([3.2, 4.8])

### 习题一

完成下面的函数代码，在函数中创建一个长度为4的三个一维numpy数列A, B，C. A的元素为1,2,3,4，B的元素为5,6,7,8，C的元素为0,0,0,0。最后返回数列A，B，C以及他们的和。请注意不要使用循环语句遍历数列。

In [18]:
def create_and_add_arrays():
    """创建numpy数组并相加"""
    # A = ... # 创建数列A，包含1, 2, 3, 4
    # B = ... # 创建数列B，包含5, 6, 7, 8
    # C = ... # 创建数列C，包含4个0
    # D = ... # 创建数列D，等于前面3个数列的和
    # 大约需要4行代码，注意不要使用循环

    # 你编写的代码从这里开始
    A = np.array([1, 2, 3, 4])
    B = np.array([5, 6, 7, 8])
    C = np.zeros(4)
    D = A + B + C

    # 你编写的代码到这里结束
    return A, B, C, D

In [19]:
test_create_and_add_arrays(create_and_add_arrays)

恭喜你通过了习题一: test_create_and_add_arrays测试。1/7 


### 索引和切片

numpy数组的索引和切片和Python的列表类似，但是有一些特殊的地方。

![索引和切片](./img/2023-10-27-11-35-38.png)

In [20]:
data = np.array([1, 2, 3])
print(data[0])
print(data[-1])
print(data[0:2])
print(data[1:])
print(data[::-1])

1
3
[1 2]
[2 3]
[3 2 1]


### 一维数据的聚合

![数据的聚合](./img/2023-10-27-11-40-03.png)

In [21]:
data = np.array([1, 2, 3])
print(data)

# 求最大值、最小值、求和
print(data.max())
print(data.min())
print(data.sum())

# 求均值、标准差
print(data.mean())
print(data.std())

# 求最大值、最小值的索引
print(data.argmax())   # 返回2，即最大值3的索引
print(data.argmin())   # 返回0，即最小值1的索引

[1 2 3]
3
1
6
2.0
0.816496580927726
2
0


### 习题二

函数的输入是两个一维numpy数列A和B(数列都不为空)，返回数列A中的最大值与和数列B的最小值的乘积。请注意不要使用循环语句遍历数列。

In [22]:
def multiply_max_min(A, B):
    """返回数列A最大值和数列B最小值的乘积"""
    # 只需要1行代码
    # 你编写的代码从这里开始


    # 你编写的代码到这里结束
    result = A.max() * B.min()
    return result

In [23]:
test_multiply_max_min(multiply_max_min)

恭喜你通过了习题二: test_multiply_max_min测试。2/7 


### 二维矩阵

![创建二维矩阵](./img/2023-10-27-11-52-59.png)

In [24]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

![创建多维数据](./img/2023-10-27-11-54-20.png)

In [25]:
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [27]:
print(np.random.random((3,2)))

[[0.20456028 0.56772503]
 [0.5955447  0.96451452]
 [0.6531771  0.74890664]]


In [28]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
# 单元矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 二维矩阵的索引和切片

![](./img/2023-10-27-12-08-39.png)

In [30]:
data = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
print(data)

# 使用行索引和列索引选择到一个元素
print(data[0, 1])

# 使用行索引的切片
print(data[1:3,:])

# 行索引和列索引同时使用切片
print(data[0:2, ::2])

[[1 2 3]
 [3 4 7]
 [5 6 9]]
2
[[3 4 7]
 [5 6 9]]
[[1 3]
 [3 7]]


### 习题三

已知一个二维的numpy矩阵stocks，其中每一行代表若干只股票某天的收盘价格，每一列代表某只股票连续若干天的价格。请完成函数代码，获取每只股票从第一天开始每三天的价格。请注意不要使用循环语句遍历矩阵。

例如：
```
stocks = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30],
                    [31,32,33,34,35,36,37,38,39,40]])       
``` 
返回结果为：
```
np.array([[1,2,3,4,5,6,7,8,9,10],
            [31,32,33,34,35,36,37,38,39,40]]) 
```

In [31]:
def get_stocks_price(data):
    """获取股票的收盘价"""
    # 只需要1行代码
    # 你编写的代码从这里开始

    # 你编写的代码到这里结束
    result = data[::3, :]
    return result

In [32]:
from testset5 import test_get_stocks_price
test_get_stocks_price(get_stocks_price)

恭喜你通过了习题三test_get_stocks_price测试。3/7 


### 矩阵运算🧮

![矩阵加法](./img/2023-10-27-12-03-47.png)

In [33]:
data = np.array([[1, 2], [3, 4]])
ones = np.ones([2, 2])
data + ones

array([[2., 3.],
       [4., 5.]])

![按行相加](./img/2023-10-27-12-04-55.png)

In [34]:
data = np.array([[1, 2], [3, 4], [5, 6]])
# 按行相加
ones_row = np.ones([1, 1])
data + ones_row

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [35]:
# 按列相加
column_data = np.array([10, 20, 30])

# 转换为列向量
print(column_data[:, np.newaxis])

data + column_data[:, np.newaxis]

[[10]
 [20]
 [30]]


array([[11, 12],
       [23, 24],
       [35, 36]])

### 矩阵的转置和变形

![矩阵装置](./img/2023-10-27-13-40-49.png)

In [36]:
# 矩阵转置
data = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
data.T

array([[1, 3, 5],
       [2, 4, 6]])

![reshape matrix](./img/2023-10-27-13-42-39.png)

In [37]:
data = np.arange(1, 7)
print(data)
print(data.reshape(2, 3))  # 转换成2 * 3的矩阵
print(data.reshape(3, 2))
print(data.reshape(6, 1))  # 转换成6 * 1的矩阵
print(data.reshape(6,))    # 转换成一维的 1 * 6 的数列

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [38]:
data = np.arange(1, 7)
print(data)

# 在reshape函数中，如果指定一个维度为-1，那么reshape函数会自动计算这个维度的大小
print(data.reshape(2, -1))  # 推算出第二个维度应该为3，转换成2 * 3的矩阵
print(data.reshape(-1, 2))  # 推算出第一个维度应该为3，转换成3 * 2的矩阵
print(data.reshape(-1,))    # 推算出第一个维度应该为6，转换成一维的 1 * 6 的数列

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### 习题四

下面的函数输入是二维矩阵`A`, 要求函数获取到`A`的形状`shape`，根据形状计算矩阵A元素个数，并将`A`转换成一维数列B，最后将数列B中的元素逆序排列后,函数返回`shape`和逆序后的数列`B`。请注意不要使用循环语句遍历矩阵。

例如：
```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
```

返回值应该如下：
```python
((3, 3), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))
```

In [39]:
def reshape_and_reverse(A):
    """获取矩阵形状，变形矩阵，逆序数列"""
    # shape = ...    # 获取矩阵A的形状
    # B = ...        # 将矩阵A转换成数列B
    # B = ...        # 将数列B逆序
    # 大约需要3行代码
    # 你编写的代码从这里开始

    # 你编写的代码到这里结束
    shape = A.shape
    B = A.reshape(-1,)
    return shape, B[::-1]

In [40]:
M = np.arange(1, 10)
reshape_and_reverse(M.reshape(3,3))
# 输出的结果应该是： ((3, 3), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))

((3, 3), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))

In [41]:
# 测试你的程序
from testset5 import test_reshape_and_reverse
test_reshape_and_reverse(reshape_and_reverse)

恭喜你通过了习题四test_reshape_and_reverse测试。4/7 


### 线性代数

![dot product](./img/2023-10-27-13-11-55.png)

In [42]:
# 点乘
data = np.array([1, 2, 3])
power_of_tens = np.array([[1, 10],
                        [100, 1000],
                        [10000, 100000]])
data.dot(power_of_tens)

array([ 30201, 302010])

In [43]:
# @符号表示点乘，也就是矩阵乘法
data @ power_of_tens

array([ 30201, 302010])

In [44]:
# 矩阵求逆
data = np.array([[1, 2], [3, 4]])
np.linalg.inv(data)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
# 矩阵行列式
np.linalg.det(data)

-2.0000000000000004

### 习题五

下面的函数输入参数是两个二维矩阵`A`和`B`，要求函数计算`A`和`B`的矩阵乘积，将乘积结果的矩阵(乘积结果不是奇异矩阵并且可逆)求逆后返回结果。请注意不要使用循环语句遍历矩阵。

例如：
```python
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [1, 0],
    [0, 1],
])
```

返回值应该如下：
```python
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
```

In [46]:
def matrix_product_and_inverse(A, B):
    """
    计算矩阵A和B的乘积,然后求逆
    """
    # product = ...    # 计算矩阵A和B的乘积
    # inverse = ...    # 矩阵求逆
    # 大约需要2行代码
    # 你编写的代码从这里开始

    # 你编写的代码到这里结束
    product = np.dot(A, B)
    inverse = np.linalg.inv(product)
    return inverse

In [47]:
m1 = np.array([
    [1, 2],
    [3, 4]
])
m2 = np.eye(2)
matrix_product_and_inverse(m1, m2)
# 输出结果应该是： array([[-2. ,  1. ],  [ 1.5, -0.5]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [48]:
from testset5 import test_matrix_product_and_inverse
test_matrix_product_and_inverse(matrix_product_and_inverse)

恭喜你通过了习题6test_matrix_product_and_inverse测试。5/7 


### 矩阵的聚合

![矩阵聚合一](./img/2023-10-27-13-33-54.png)

In [49]:
data = np.array([[1, 2],[5, 3], [4, 6]])
print(data.max())
print(data.min())
print(data.sum())

6
1
21


![矩阵聚合二](./img/2023-10-27-13-34-55.png)

In [50]:
print(data)
print('求每列最大值:',data.max(axis=0))

print('求每行最大值:',data.max(axis=1))

print('计算每列的和:',data.sum(axis=0))

print('计算每行的和:',data.sum(axis=1))

print('计算每列的平均值:', data.mean(axis=0))

[[1 2]
 [5 3]
 [4 6]]
求每列最大值: [5 6]
求每行最大值: [2 5 6]
计算每列的和: [10 11]
计算每行的和: [ 3  8 10]
计算每列的平均值: [3.33333333 3.66666667]


### 习题六

下面函数的输入参数是二维矩阵，存储了某班级学生的各科的成绩，每一行代表一个学生的各科成绩，每一列代表一门课程的所有学生的成绩。要求函数计算每门课程的平均成绩和每个学生的总成绩。请注意不要使用循环语句遍历矩阵。

例如：
```python
scores = np.array([
    [80, 90, 85],
    [70, 60, 65],
    [90, 80, 85],
    [85, 75, 80],
    [60, 70, 75],
])
```

返回值应该如下：
```python
(array([77., 75., 78.]), array([255., 195., 255., 240., 205.]))
```

In [51]:
def compute_scores(scores):
    """
    计算每个学生的总分和每门科目的平均分
    """
    # mean = ...     # 计算每个科目的平均分
    # total = ...    # 计算每个学生的总分
    # 大约需要2行代码
    # 你编写的代码从这里开始


    # 你编写的代码到这里结束
    total = scores.sum(axis=1)
    mean = scores.mean(axis=0)
    return  mean, total

In [52]:
scores = np.array([
    [80, 90, 85],
    [70, 60, 65],
    [90, 80, 85],
    [85, 75, 80],
    [60, 70, 75],
])
compute_scores(scores)
# 输出结果应该是： (array([77. , 75. , 78.]), array([255, 195, 255, 240, 205]))

(array([77., 75., 78.]), array([255, 195, 255, 240, 205]))

In [53]:
# 测试你的程序
from testset5 import test_compute_scores
test_compute_scores(compute_scores)

恭喜你通过了习题6 test_compute_scores 测试。6/7


### 更高维的数组（tensor--张量）

![](./img/2023-10-27-14-11-21.png)

In [54]:
np.arange(1,9).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
print(np.ones((4, 3, 2)))
print(np.zeros((4, 3, 2)))
print(np.random.random((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[0.65356987 0.74771481]
  [0.96130674 0.0083883 ]
  [0.10644438 0.29870371]]

 [[0.65641118 0.80981255]
  [0.87217591 0.9646476 ]
  [0.72368535 0.64247533]]

 [[0.71745362 0.46759901]
  [0.32558468 0.43964461]
  [0.72968908 0.99401459]]

 [[0.67687371 0.79082252]
  [0.17091426 0.02684928]
  [0.80037024 0.90372254]]]


### Numpy的应用

- 线性代数，统计学方面的运算
- 表示各种类型的数据：图像，音频，文本
- 用于机器学习和深度学习的算法

![表示音频数据](./img/2023-10-27-14-19-04.png)

![image data](./img/2023-10-27-14-20-34.png)

![colorful image](./img/2023-10-27-14-21-52.png)

## Pandas🐼

### `Pandas`数据结构

`Pandas`是基于`Numpy`的一个数据处理库，提供了两种数据结构：`Series`和`DataFrame`。

- `Series`是一个一维的数据结构，类似于`Numpy`中的一维数组，不同的是`Series`可以有非整数的索引（被称作标签），可以通过标签来访问数据。
- `DataFrame`是一个二维的数据结构，类似于电子表格或者SQL表，可以存储多种类型的数据，可以通过行和列的索引(可以不是整数)来访问数据, `DataFrame`可以看作是由多个`Series`组成的。

### 加载数据

![加载数据](./img/2023-10-31-07-58-44.png)

In [56]:
import pandas as pd

# 读取csv文件,得到二维结构的数据： DataFrame
df = pd.read_csv('./data/music.csv')
df

Artist Genre  Listeners     Plays
0  Billie Holiday  Jazz    1300000  27000000
1    Jimi Hendrix  Rock    2700000  70000000
2     Miles Davis  Jazz    1500000  48000000
3             SIA   Pop    2000000  74000000

pandas可以从下面这些来源加载数据：

- CSV
- Excel
- HTML
- JSON
- SQL
- API
- 等等其他

### 选择数据

In [57]:
# 按照列名选择数据
df['Artist']

0    Billie Holiday
1      Jimi Hendrix
2       Miles Davis
3               SIA
Name: Artist, dtype: object

In [58]:
# 选择多列数据
df[['Artist', 'Plays']]

Artist     Plays
0  Billie Holiday  27000000
1    Jimi Hendrix  70000000
2     Miles Davis  48000000
3             SIA  74000000

In [59]:
# 按照行索引选择数据
df[1:3]

Artist Genre  Listeners     Plays
1  Jimi Hendrix  Rock    2700000  70000000
2   Miles Davis  Jazz    1500000  48000000

In [60]:
# 按照行索引和列索引选择数据
df.loc[1:3, ['Artist', 'Plays']]

Artist     Plays
1  Jimi Hendrix  70000000
2   Miles Davis  48000000
3           SIA  74000000

### 过滤数据

In [61]:
df[df['Genre']=='Jazz']

Artist Genre  Listeners     Plays
0  Billie Holiday  Jazz    1300000  27000000
2     Miles Davis  Jazz    1500000  48000000

In [62]:
df[df['Listeners'] > 1800000]

Artist Genre  Listeners     Plays
1  Jimi Hendrix  Rock    2700000  70000000
3           SIA   Pop    2000000  74000000

### 处理数据缺失的情况

![dropna](./img/2023-10-31-08-20-30.png)

In [63]:
df2 = pd.read_csv('./data/music copy.csv')
df2

Artist   Genre  Listeners       Plays
0  Billie Holiday   Jazz     1300000  27000000.0
1  Jimi Hendrix     Rock     2700000         NaN
2  Miles Davis      Jazz     1500000  48000000.0
3  SIA              Pop      2000000  74000000.0

In [64]:
df2.dropna()

Artist   Genre  Listeners       Plays
0  Billie Holiday   Jazz     1300000  27000000.0
2  Miles Davis      Jazz     1500000  48000000.0
3  SIA              Pop      2000000  74000000.0

In [65]:
df2.fillna(method='ffill')

Artist   Genre  Listeners       Plays
0  Billie Holiday   Jazz     1300000  27000000.0
1  Jimi Hendrix     Rock     2700000  27000000.0
2  Miles Davis      Jazz     1500000  48000000.0
3  SIA              Pop      2000000  74000000.0

### Grouping

In [66]:
df.groupby('Genre').sum()

Listeners     Plays
Genre                     
Jazz     2800000  75000000
Pop      2000000  74000000
Rock     2700000  70000000

### 创建新的列

In [67]:
# 计算每个歌手的平均播放量
df['Avg Plays'] = df['Plays'] / df['Listeners']
df

Artist Genre  Listeners     Plays  Avg Plays
0  Billie Holiday  Jazz    1300000  27000000  20.769231
1    Jimi Hendrix  Rock    2700000  70000000  25.925926
2     Miles Davis  Jazz    1500000  48000000  32.000000
3             SIA   Pop    2000000  74000000  37.000000

### 习题七

函数输入的DataFrame数据格式如下：

| 列名         | 类型    |  
|--------------|---------|  
| name         | varchar |  
| continent    | varchar |  
| area         | int     |  
| population   | int     |  
| gdp          | bigint  |

**`name` 是表的主键（具有唯一值的列）。**  
表中的每一行提供了一个国家的信息，包括国家名称、所属大陆、国土面积、人口数量以及 GDP 值。

---

**一个国家被认为是“大国”如果：**  
- 它的国土面积至少为 3,000,000 平方千米（即 3000000 km²）；或  
- 它的人口数量至少为 25,000,000（即 25000000）。  

请编写一个函数，查询“大国”的名称、人口和国土面积，返回结果表的顺序可以任意。请注意不要使用循环语句遍历数据。

---

例如：

**输入：**  
World 表：  
| name        | continent | area    | population | gdp          |  
|-------------|-----------|---------|------------|--------------|  
| Afghanistan | Asia      | 652230  | 25500100   | 20343000000  |  
| Albania     | Europe    | 28748   | 2831741    | 12960000000  |  
| Algeria     | Africa    | 2381741 | 37100000   | 188681000000 |  
| Andorra     | Europe    | 468     | 78115      | 3712000000   |  
| Angola      | Africa    | 1246700 | 20609294   | 100990000000 |  

**输出：**  
| name        | population | area    |  
|-------------|------------|---------|  
| Afghanistan | 25500100   | 652230  |  
| Algeria     | 37100000   | 2381741 |


In [68]:
def big_countries(df):
    """
    获取“大国”的国家名称、人口和面积。
    一个国家被认为是“大国”如果：
    - 面积至少为 3,000,000 平方千米 (3000000) 或
    - 人口至少为 25,000,000 (25000000)
    """

    # big_countries = ...    # 过滤获取人口至少为25000000或者（使用“|”操作符）面积至少为3000000的国家
    # result = ...            # 查询“大国”的名称、人口和国土面积这三列的数据
    # 大约需要3行代码
    # 你编写的代码从这里开始

    result = df.loc[(df['area'] >= 3000000) | (df['population'] >= 25000000), ['name', 'population', 'area']]
    # 你编写的代码到这里结束
    return result

In [69]:
data = {
    "name": ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola"],
    "continent": ["Asia", "Europe", "Africa", "Europe", "Africa"],
    "area": [652230, 28748, 2381741, 468, 1246700],
    "population": [25500100, 2831741, 37100000, 78115, 20609294],
    "gdp": [20343000000, 12960000000, 188681000000, 3712000000, 100990000000]
}
df = pd.DataFrame(data)
print(big_countries(df))
# 输出结果应该是：
#           name  population     area
# 0  Afghanistan    25500100   652230
# 2      Algeria    37100000  2381741

          name  population     area
0  Afghanistan    25500100   652230
2      Algeria    37100000  2381741


In [70]:
# 测试你的程序
from testset5 import test_big_countries
test_big_countries(big_countries)

恭喜你通过了习题7test_big_countries测试。7/7 


## 扩展阅读📖

- Numpy文章：[A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)

- Numpy文章的中文版：[Numpy和数据展示的可视化介绍](http://www.junphy.com/wordpress/index.php/2019/10/24/visual-numpy)

- Pandas文章:[A Gentle Visual Intro to Data Analysis in Python Using Pandas](https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas)

参考书：[利用Python进行数据分析（原书第3版)](https://m.douban.com/book/subject/36632126/)

github地址：[利用Python进行数据分析（原书第3版)源代码](https://github.com/wesm/pydata-book)

## 实验自动评分

请运行下面的代码进行实验自动评分

In [71]:
from testset5 import grade_all_tests
grade_all_tests([create_and_add_arrays,
    multiply_max_min,
    get_stocks_price,
    reshape_and_reverse,
    matrix_product_and_inverse,
    compute_scores,
    big_countries,])

恭喜你通过了习题一: test_create_and_add_arrays测试。1/7 
恭喜你通过了习题二: test_multiply_max_min测试。2/7 
恭喜你通过了习题三test_get_stocks_price测试。3/7 
恭喜你通过了习题四test_reshape_and_reverse测试。4/7 
恭喜你通过了习题6test_matrix_product_and_inverse测试。5/7 
恭喜你通过了习题6 test_compute_scores 测试。6/7
恭喜你通过了习题7test_big_countries测试。7/7 
恭喜你7/7 个测试
你的代码自动评分成绩是：70


## 实验总结

请尽量使用自己的语言回答下面的问题。

问题一： 为什么在对大规模数据进行计算时，要使用numpy这样的向量化操作（尽量避免使用for循环）？

问题2： 在Numpy中有哪些聚合操作，聚合操作中的axis参数是什么意思？