# 实验二：NumPy

<table style="margin: 0 auto; width: 30%; border-collapse: collapse; border: 1px solid black;" data-id="student-info">  
    <colgroup>  
        <col style="width: 35%;">  
        <col style="width: 65%;">  
    </colgroup>  
    <tr>  
        <td style="border: 1px solid black;">班级</td> <td style="border: 1px solid black;">25智能01</td>  
    </tr>  
    <tr>  
        <td style="border: 1px solid black;">学号</td> <td style="border: 1px solid black;">未填写</td>  
    </tr>  
    <tr>  
        <td style="border: 1px solid black;">姓名</td> <td style="border: 1px solid black;">未填写</td>  
    </tr>  
    <tr>  
        <td style="border: 1px solid black;">Email</td> <td style="border: 1px solid black;">123456@qq.com</td>  
    </tr>  
</table>

## 实验目的

本次实验主要学习和掌握下列内容

- 向量化（Vectorization）
- NumPy N 维数组（ndarray）的创建、选择、运算、聚合（Aggregation）与线性代数（Linear Algebra）

## 核心术语中英对照（Key Terms in Chinese and English）

本实验中的 NumPy 术语在首次集中出现时采用“中文（English）”标注，函数和属性保留 API 的英文名称。

| 中文术语 | 英文名称 | NumPy 表示或说明 |
|---|---|---|
| 向量化 | Vectorization | 用数组运算替代 Python 显式循环 |
| 标量 / 向量 / 矩阵 / 张量 | Scalar / Vector / Matrix / Tensor | 0、1、2 及更高维数据 |
| N 维数组 | N-dimensional Array | `ndarray` |
| 维度 / 轴 / 形状 | Dimension / Axis / Shape | `ndim`、`axis`、`shape` |
| 数据类型 | Data Type | `dtype` |
| 元素级运算 | Element-wise Operation | 对对应元素执行运算 |
| 广播 | Broadcasting | 自动匹配兼容形状进行数组运算 |
| 索引 / 切片 / 布尔索引 | Indexing / Slicing / Boolean Indexing | 选择数组元素或子数组 |
| 聚合 | Aggregation / Reduction | `sum()`、`mean()`、`std()` 等 |
| 转置 / 变形 / 展平 | Transpose / Reshape / Flatten | `.T`、`reshape()` |
| 点积 / 矩阵乘法 | Dot Product / Matrix Multiplication | `dot()` |
| 单位矩阵 / 对角矩阵 | Identity Matrix / Diagonal Matrix | `eye()` / `diag()` |
| 逆矩阵 / 行列式 | Matrix Inverse / Determinant | `linalg.inv()` / `linalg.det()` |
| 条件选择 | Conditional Selection | `where()` |
| 随机数生成 / 随机种子 | Random Number Generation / Random Seed | `random` / `seed()` |

## Jupyter Notebook使用指导 

1. 首先选择Python内核：在右上角点击Kernel，选择venv(...)。
2. 在编辑后首先要保存，使用Ctrl+S保存。
3. 实验运行出现问题，并且代码正确，一个最常见的解决方法在最上方点击重启(Restart), 然后点击运行所有（Run All）。
4. 如果仍然出现问题，请保存后关闭notebook，然后重复步骤3。

## 实验准备

首先，让我们运行下面的单元格来导入您在此作业中需要的所有包, 并且为实验的代码的测试做准备。

In [ ]:
# 导入需要的Python包
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import sys
from IPython.display import display, Image

# 获取项目根目录
project_root = Path().resolve().parent
sys.path.append(str(project_root / 'tests'))
sys.path.append(str(project_root / 'util'))

# 导入测试套件和其他工具
from test_suite2 import TestSuite2
from lr_utils import load_dataset
from notebook2pdf import convert_notebook_to_webpdf
from notebook_info_extractor import extract_from_ipynb, is_valid_email
from IPython import get_ipython

testsuite2 = TestSuite2()

ip = get_ipython()
notebook_file = None
if '__vsc_ipynb_file__' in ip.user_ns:
    notebook_file = ip.user_ns['__vsc_ipynb_file__']

stu_info = extract_from_ipynb(notebook_file)

if is_valid_email(stu_info.get("email")):
    print(f"stu_info: {stu_info}")
else:
    print(
        "Email地址无效，请在Notebook顶部的学生信息表中重新输入有效的Email地址，"
        "保存Notebook后重新运行本单元格。"
    )

## 实验注意事项

1. 请在指定的地方按照实验指导要求来编写代码。
2. 请按照实验指导要求使用指定的变量名或函数名，不要使用其他的名字。
3. 不要添加任何额外的语句。
4. 不要添加任何额外的代码单元格。
5. 不要在不需要的地方修改作业代码，比如创建额外的变量，修改测试文件中的代码。
6. 实验指导中的`...`表示需要你补充代码的部分，其他部分的代码不用修改。
7. 代码提示中会给出估计的代码行数，例如大约1行代码，估计的代码行数只是一个参考值，实际编写时可能会有出入，请根据实际情况来编写。
8. 请独立完成作业，禁止抄袭，发现抄袭行为成绩记零分

## 向量化（Vectorization）

`NumPy`在数据分析和机器学习中都被大量地使用，通常逆需要处理非常大的数据集。因此，一个非计算高效的函数可能会成为算法中的巨大瓶颈，为了确保代码具有计算效率，你需要使用向量化操作。

- 利用`numpy`和`pandas`的函数或操作对整个数组或数组的子集进行操作
- 尽可能避免使用`for`循环和`while`循环逐个处理数据集中的元素
- 向量化操作的编程范式在数据分析、机器学习领域被大量地使用，例如下面这些最流行的深度学习框架
  - `pytorch`
  - `tensorflow`
  - ...  

## NumPy 数组计算（NumPy Array Computing）🐍

In [ ]:
# 安装numpy模块
# %pip install numpy

### 为什么需要 NumPy（Why NumPy）❓

- 运行速度：NumPy提供了高效的数组操作功能(向量化操作)，可以对大规模的数据进行快速的计算和处理
- 方便使用: 处理数据的过程更加简洁和高效
- 功能丰富：提供了丰富的函数库，可以方便地进行数值计算和统计分析。

In [ ]:
# 导入numpy
import numpy as np
np.random.seed(12345)

In [ ]:
# 长度100万的numpy格式的数组
my_arr = np.arange(1_000_000)

# 长度100万的list
my_list = list(range(1_000_000))

- 计算数组中一百万个数的平方，使用`timeit`测试两种方法的运行时间
- 结论：因为`numpy`的向量化操作，所以运行速度远远快过使用for循环的list。

In [ ]:
# print('numpy running time:')
# %timeit my_arr2 = my_arr ** 2

# print('\npython list running time:')
# %timeit my_list2 = [x ** 2 for x in my_list]

### NumPy N 维数组数据结构（ndarray Data Structure）

numpy只有一种数据结构：ndarray，它是一个多维数组，每个元素都是相同类型的。

In [ ]:
display(Image("./img/2023-10-27-11-02-03.png", width=800, height=400))

In [ ]:
import numpy as np

data = np.array([1, 2, 3])
data

In [ ]:
# ndarray的数据类型,数组只能包含相同类型的数据
data.dtype

### 创建 N 维数组（Creating an ndarray）

In [ ]:
display(Image("./img/2023-10-27-11-06-02.png", width=800, height=400))

In [ ]:
# 创建全为1的数组
np.ones(3)

In [ ]:
# 创建全为0的数组
np.zeros(3)

In [ ]:
# 创建随机数组，长度为3，数值在0-1之间
np.random.random(3)

In [ ]:
# 类似Python中的range函数
np.arange(10)

In [ ]:
# 创建形状相同，数值全为1的数组
np.ones_like([1, 2, 3, 4, 5])

In [ ]:
# 创建形状相同，数值全为0的数组
np.zeros_like([1, 2, 3, 4, 5])

In [ ]:
# 使用lambda函数创建一个3*3的矩阵, 矩阵的元素的值为i+j
np.fromfunction(lambda i, j: i + j, (3, 3))

### 算术运算（Arithmetic Operations）

`Numpy`中的算术运算可以利用广播（broadcasting）的特性，使得运算自动应用到数组中的所有元素。

In [ ]:
display(Image("./img/2023-10-27-11-16-15.png", width=800, height=600))

In [ ]:
import numpy as np
data = np.array([1, 2, 3])
ones = np.ones_like(data)
data + ones

In [ ]:
# 其他运算
display(Image("./img/2023-10-27-11-18-34.png", width=800, height=400))

In [ ]:
data - ones

In [ ]:
data * data

In [ ]:
data / data

In [ ]:
data = np.array([2, 3])
print(data)
data ** data

In [ ]:
# 数组乘以一个标量
display(Image("./img/2023-10-27-11-20-07.png", width=800, height=400))

In [ ]:
data = np.array([1, 2])
data * 1.6

如果想要对数列进行四则混合运算或者更复杂的操作，可以使用`lambda`函数对数列进行向量化操作。例如要对数列中所有的元素`x`进行运算： `x ** 2 + 1`。

In [ ]:
arr = np.arange(5)
(lambda x: x ** 2 + 1)(arr)

### 习题一

完成下面的函数代码:
- 输入参数为整数n, 函数要求创建三个长度为n的一维numpy数列A,B,C和D;
- 数列A中的元素最大为n-1，请使用`np.arange`函数创建数列A；
- 数列B的元素全是n，请使用`np.ones`或者`np.ones_like`函数创建数列B；
- C的元素全是0，请使用`np.zeros_like`函数创建数列C；
- 最后返回数列A，B，C以及他们的和D。
- 注意不要使用循环语句遍历数列。

In [ ]:
# UNQ_C1 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: create_and_add_arrays

def create_and_add_arrays(n: int):
    """创建numpy数组并相加"""

    # 大约需要4行代码，注意不要使用循环

    # 你编写的代码从这里开始
    A = ... # 创建数列A: (0, 1, 2, ... , n-1), 要使用np.arange函数
    B = ... # 创建数列B，要使用np.ones_like函数
    C = ... # 创建数列C，要使用np.zeros_like函数
    D = ... # 创建数列D，等于前面3个数列的和

    # 你编写的代码到这里结束
    return A, B, C, D

In [ ]:
# 测试习题1
testsuite2.test_create_and_add_arrays(create_and_add_arrays)

### 索引和切片（Indexing and Slicing）

numpy数组的索引和切片和Python的列表类似，但是有一些特殊的地方。

In [ ]:
display(Image("./img/2023-10-27-11-35-38.png", width=800, height=400))

In [ ]:
data = np.array([1, 2, 3])
print(data[0])
print(data[-1])
print(data[0:2])
print(data[1:])
print(data[::-1]) # 倒序

### 一维数据的聚合（One-dimensional Aggregation）

In [ ]:
display(Image("./img/2023-10-27-11-40-03.png", width=800, height=400))

In [ ]:
data = np.array([1, 2, 3])
print(data)

# 求最大值、最小值、求和
print(data.max())
print(data.min())
print(data.sum())

# 求均值、标准差
print(data.mean())
print(data.std())

# 求最大值、最小值的索引
print(data.argmax())   # 返回2，即最大值3的索引
print(data.argmin())   # 返回0，即最小值1的索引

# 排序
data = np.array([9, 3, 5, 7, 1, 2])
data.sort()
print(data)

### 习题二

函数的输入是两个一维numpy数列A和B(数列都不为空)，返回数列A中的最大值与和数列B的最小值的乘积。请注意不要使用循环语句遍历数列。

In [ ]:
# UNQ_C2 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: multiply_max_min

def multiply_max_min(A, B):
    """返回数列A最大值和数列B最小值的乘积"""
    # 只需要1行代码
    # 你编写的代码从这里开始
    result = ...

    # 你编写的代码到这里结束
    return result

In [ ]:
# 测试习题2
testsuite2.test_multiply_max_min(multiply_max_min)

### 二维矩阵（Two-dimensional Matrix）

In [ ]:
display(Image("./img/2023-10-27-11-52-59.png", width=800, height=400))

In [ ]:
data = np.array([[1, 2], [3, 4]])
data

![创建多维数据](./img/2023-10-27-11-54-20.png)

In [ ]:
print(np.ones((3,2)))

In [ ]:
print(np.zeros((3,2)))

In [ ]:
print(np.random.random((3,2)))

In [ ]:
np.diag([1, 2, 3])

In [ ]:
# 单元矩阵
np.eye(3)

### 二维矩阵的索引和切片（Matrix Indexing and Slicing）

In [ ]:
display(Image("./img/2023-10-27-12-08-39.png", width=800, height=400))

In [ ]:
data = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
print(data)

# 使用行索引和列索引选择到一个元素
print(data[0, 1])

# 使用行索引的切片
print(data[1:3,:])

# 行索引和列索引同时使用切片
print(data[0:2, ::2])

### 习题三

已知一个二维的numpy矩阵stocks，其中每一行代表若干只股票某天的收盘价格，每一列代表某只股票连续若干天的价格。请完成函数代码，获取每只股票从第一天开始每三天的价格。请注意不要使用循环语句遍历矩阵。

例如：
```
stocks = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30],
                    [31,32,33,34,35,36,37,38,39,40]])       
``` 
返回结果为：
```
np.array([[1,2,3,4,5,6,7,8,9,10],
            [31,32,33,34,35,36,37,38,39,40]]) 
```

In [ ]:
# UNQ_C3 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: get_stocks_price

def get_stocks_price(stocks):
    """获取股票的收盘价"""
    # 只需要1行代码, 请使用切片
    # 你编写的代码从这里开始
    result = ...

    # 你编写的代码到这里结束
    return result

In [ ]:
# 测试习题3
testsuite2.test_get_stocks_price(get_stocks_price)

### 矩阵运算（Matrix Operations）🧮

二维的`Numpy`矩阵同样具有广播(Broadcasting)特性，稍微不同的是，`Numpy`会根据运算的矩阵的形状将运算自动广播到行、列或者每个元素上。

In [ ]:
display(Image("./img/2023-10-27-12-03-47.png", width=800, height=400))

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.ones([2, 2])
data + ones

In [ ]:
display(Image("./img/2023-10-27-12-04-55.png", width=800, height=400))

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
# 按行相加，广播到行
ones_row = np.ones([1, 1])
data + ones_row

In [ ]:
print("data:\n", data)

# 按列相加， 广播到列
column_data = np.array([10, 20, 30])

# 转换为列向量
print("column:\n", column_data[:, np.newaxis])

data + column_data[:, np.newaxis]

### 矩阵的转置和变形（Transpose and Reshape）

In [ ]:
display(Image("./img/2023-10-27-13-40-49.png", width=800, height=400))

In [ ]:
# 矩阵转置
data = np.array([[1, 2],
                    [3, 4],
                    [5, 6]])
data.T

In [ ]:
display(Image("./img/2023-10-27-13-42-39.png", width=800, height=400))

In [ ]:
data = np.arange(1, 7)
print(data)
print(data.reshape(2, 3))  # 转换成2 * 3的矩阵
print(data.reshape(3, 2))
print(data.reshape(6, 1))  # 转换成6 * 1的矩阵
print(data.reshape(6,))    # 转换成一维的 1 * 6 的数列

In [ ]:
data = np.arange(1, 7)
print(data)

# 在reshape函数中，如果指定一个维度为-1，那么reshape函数会自动计算这个维度的大小
print(data.reshape(2, -1))  # 推算出第二个维度应该为3，转换成2 * 3的矩阵
print(data.reshape(-1, 2))  # 推算出第一个维度应该为3，转换成3 * 2的矩阵
print(data.reshape(-1,))    # 推算出第一个维度应该为6，转换成一维的 1 * 6 的数列

### 习题四

下面的函数输入是二维矩阵`A`, 要求函数获取到`A`的形状`shape`，然后将`A`转换成一维数列B，最后将数列B中的元素逆序排列后,函数返回`shape`和逆序后的数列`B`。请注意不要使用循环语句遍历矩阵。

例如：
```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
```

返回值应该如下：
```python
((3, 3), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))
```

In [ ]:
# UNQ_C4 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: reshape_and_reverse

def reshape_and_reverse(A):
    """获取矩阵形状，变形矩阵，逆序数列"""

    # 大约需要2-3行代码
    # 你编写的代码从这里开始
    shape = ...    # 获取矩阵A的形状
    B = ...        # 将矩阵A转换成数列B
    B = ...        # 将数列B逆序
    # 你编写的代码到这里结束
    return shape, B

In [ ]:
M = np.arange(1, 10)
reshape_and_reverse(M.reshape(3,3))
# 输出的结果应该是： ((3, 3), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))

In [ ]:
# 测试习题4
testsuite2.test_reshape_and_reverse(reshape_and_reverse)

### 线性代数（Linear Algebra）

In [ ]:
display(Image("./img/2023-10-27-13-11-55.png", width=600, height=400))

In [ ]:
# 点乘
data = np.array([1, 2, 3])
power_of_tens = np.array([[1, 10],
                        [100, 1000],
                        [10000, 100000]])
data.dot(power_of_tens)

In [ ]:
# 二维矩阵也可以使用@符号进行点乘乘法,
# 但是更高维的数列则必须使用np.dot()来进行点乘
data @ power_of_tens   # 相当于调用了np.matmul()函数

In [ ]:
# 矩阵求逆
data = np.array([[1, 2], [3, 4]])
np.linalg.inv(data)

In [ ]:
# 矩阵行列式
np.linalg.det(data)

### 习题五

下面的函数输入参数是两个二维矩阵`A`和`B`，要求函数计算`A`和`B`的矩阵乘积，将乘积结果的矩阵(乘积结果不是奇异矩阵并且可逆)求逆后返回结果。请注意不要使用循环语句遍历矩阵。

例如：
```python
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [1, 0],
    [0, 1],
])
```

返回值应该如下：
```python
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
```

In [ ]:
# UNQ_C5 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: matrix_product_and_inverse

def matrix_product_and_inverse(A, B):
    """
    计算矩阵A和B的乘积,然后求逆
    """

    # 大约需要2行代码
    # 你编写的代码从这里开始
    product = ...    # 计算矩阵A和B的乘积
    inverse = ...    # 矩阵求逆
    # 你编写的代码到这里结束

    return inverse

In [ ]:
m1 = np.array([
    [1, 2],
    [3, 4]
])
m2 = np.eye(2)
matrix_product_and_inverse(m1, m2)
# 输出结果应该是： array([[-2. ,  1. ],  [ 1.5, -0.5]])

In [ ]:
# 测试习题5
testsuite2.test_matrix_product_and_inverse(matrix_product_and_inverse)

### 矩阵的聚合（Matrix Aggregation）

In [ ]:
display(Image("./img/2023-10-27-13-33-54.png", width=800, height=400))

In [ ]:
data = np.array([[1, 2],[5, 3], [4, 6]])
print(data.max())
print(data.min())
print(data.sum())

In [ ]:
display(Image("./img/2023-10-27-13-34-55.png", width=800, height=400))

In [ ]:
print(data)
print('求每列最大值:',data.max(axis=0))

print('求每行最大值:',data.max(axis=1))

print('计算每列的和:',data.sum(axis=0))

print('计算每行的和:',data.sum(axis=1))

print('计算每列的平均值:', data.mean(axis=0))

### 习题六

下面函数的输入参数是二维矩阵，存储了某班级学生的各科的成绩，每一行代表一个学生的各科成绩，每一列代表一门课程的所有学生的成绩。要求函数计算每门课程的平均成绩和每个学生的总成绩。请注意不要使用循环语句遍历矩阵。

例如：
```python
scores = np.array([
    [80, 90, 85],
    [70, 60, 65],
    [90, 80, 85],
    [85, 75, 80],
    [60, 70, 75],
])
```

返回值应该如下：
```python
(array([77., 75., 78.]), array([255., 195., 255., 240., 205.]))
```

In [ ]:
# UNQ_C6 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: compute_scores

def compute_scores(scores):
    """
    计算每个学生的总分和每门科目的平均分
    """

    # 大约需要2行代码
    # 你编写的代码从这里开始
    mean = ...     # 计算每个科目的平均分
    total = ...    # 计算每个学生的总分

    # 你编写的代码到这里结束

    return  mean, total

In [ ]:
scores = np.array([
    [80, 90, 85],
    [70, 60, 65],
    [90, 80, 85],
    [85, 75, 80],
    [60, 70, 75],
])
compute_scores(scores)
# 输出结果应该是： (array([77. , 75. , 78.]), array([255, 195, 255, 240, 205]))

In [ ]:
# 测试习题6
testsuite2.test_compute_scores(compute_scores)

### 数组中的条件逻辑（Conditional Logic with Arrays）

`numpy.where`语句是向量化的`if else`语句

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

如果条件数列`cond`的元素为`True`，我们就取xarr中的元素，如果为`False`，我们就取yarr中的元素。

In [ ]:
# 非向量化的方法
# 这样速度会很慢, 而且也不适用于高维度的数据
result = [( x if c else y)
          for x,y,c in zip(xarr, yarr, cond)]
result

In [ ]:
# 向量化的方法
# 速度更快，并且适用于多维向量
result = np.where(cond, xarr, yarr)
result

In [ ]:
# np.where语句的第二个和第三个参数也可以是标量
arr = np.arange(5)
print(arr > 2)
np.where(arr > 2,  1,  -1)

### 习题七

完成下面的函数，函数输入是：
- scores: 考试成绩的数列
- threshold: 考试成绩及格分数（可选参数）

函数返回：
- pass_status: 考试成绩通过与否的布尔数列, True表示通过, False表示不通过
- grades: numpy数组, 包含成绩等级字符串 ('A', 'B', 'C', 'D', 'F')，A(>=90), B(>=80), C(>=70), D(>=60), F(<60)
- bonus_scores: numpy数组, 优秀学生(>=90分)获得5分奖励, 其他学生分数不变

习题要求：
- 要求使用向量化操作，不能使用循环语句
- 要求使用`np.where`语句，不能使用`if else`语句

In [ ]:
# UNQ_C7 (不要修改这两行注释，否则该习题无法生成报告)
# GRADED FUNCTION: process_exam_results

def process_exam_results(scores, pass_threshold=60):
    """
    处理考试成绩，根据分数判断通过/不通过状态和等级

    参数:
    scores: numpy数组, 包含学生成绩
    pass_threshold: 及格线, 默认为60分

    返回:
    pass_status: numpy数组, True表示通过, False表示不通过
    grades: numpy数组, 包含等级字符串 ('A', 'B', 'C', 'D', 'F')
    bonus_scores: numpy数组, 优秀学生(>=90分)获得5分奖励, 其他学生分数不变
    """

    # 大约需要3-6行代码，必须使用np.where函数
    # 你编写的代码从这里开始
    pass_status = ...
    grades = ...
    bonus_scores = ...

    # 你编写的代码到这里结束
    return pass_status, grades, bonus_scores

In [ ]:
scores = np.array([[90, 80, 70], [80, 80, 70], [70, 60, 50]])
process_exam_results(scores)
# 预期结果为：
# (array([[ True,  True,  True],
#         [ True,  True,  True],
#         [ True,  True, False]]),
#  array([['A', 'B', 'C'],
#         ['B', 'B', 'C'],
#         ['C', 'C', 'F']], dtype='<U1'),
#  array([[95, 80, 70],
#         [80, 80, 70],
#         [70, 60, 50]]))

In [ ]:
# 测试习题7
testsuite2.test_process_exam_results(process_exam_results)

### 更高维数组：张量（Higher-dimensional Arrays: Tensor）

In [ ]:
display(Image("./img/2023-10-27-14-11-21.png", width=800, height=400))

In [ ]:
np.arange(1,9).reshape(2, 2, 2)

In [ ]:
print(np.ones((4, 3, 2)))
print(np.zeros((4, 3, 2)))
print(np.random.random((4, 3, 2)))

### NumPy 的应用（Applications of NumPy）

- 线性代数，统计学方面的运算
- 表示各种类型的数据：图像，音频，文本
- 用于机器学习和深度学习的算法

In [ ]:
display(Image("./img/2023-10-27-14-19-04.png", width=800, height=800))

In [ ]:
display(Image("./img/2023-10-27-14-20-34.png", width=800, height=800))

In [ ]:
display(Image("./img/2023-10-27-14-21-52.png", width=800, height=800))

## 实验讨论

请就下面的问题进行小组讨论，将讨论的内容记录下来。

- 问题1：为什么在对大规模数据进行计算时，要使用 NumPy 这样的向量化操作（尽量避免使用 for 循环）？这样做有什么好处？

- 问题2：查找资料，NumPy 中还有哪些常见的聚合操作？聚合操作中的 axis 参数是什么意思？请举例说明。

## 生成并提交实验报告

- 在实验室环境下运行下面的代码，自动生成和提交实验报告pdf文件。
- 生成的pdf文件请自己保存。
- 非实验室环境需要补交实验报告，请将pdf文件提交到对应的班级和实验的腾讯文档收集表:[提交地址](https://docs.qq.com/form/page/DWVhDZ3JPdGRja3RP)

注意： 
1. 请同学尽可能在实验室课堂上完成实验报告提交，补交的报告会被扣除相应的分数。
2. 补交报告可以删除和修改，同一次的实验报告不要重复提交。

In [ ]:
import importlib
import notebook2pdf
importlib.reload(notebook2pdf)

stu_grade = testsuite2.grade_all_tests(notebook_file)
pdf_file = f"{stu_info['class_id']}-{stu_info['student_id']}-{stu_info['name']}-实验报告2-{stu_grade}.pdf"
notebook2pdf.convert_notebook_to_webpdf(notebook_file, pdf_file)

In [ ]:
from report_submission import submit_pdf_report

receipt = submit_pdf_report(
    pdf_file,
    stu_info,
    experiment_number=2,
)

receipt

## 参考资料📖

- NumPy文章：[A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)

- NumPy文章的中文版：[NumPy和数据展示的可视化介绍](http://www.junphy.com/wordpress/index.php/2019/10/24/visual-numpy)

参考书：[利用Python进行数据分析（原书第3版)](https://m.douban.com/book/subject/36632126/)

github地址：[利用Python进行数据分析（原书第3版)源代码](https://github.com/wesm/pydata-book)